version: '3.5'
services:
  fuseki:
    build:
      context: ./src/jena/fuseki-docker
      dockerfile: Dockerfile
    container_name: fuseki
    restart: always
    volumes:
      - rdf_data:/fuseki
      - staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - semapps
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: semapps

  middleware:
    build:
      context: ./src/middleware
      dockerfile: Dockerfile
    container_name: middleware
    restart: always
    depends_on:
      - "fuseki"
    volumes:
      - ./src/middleware:/main/
    networks:
      - semapps
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: npm run start --prefix ./boilerplates/runner
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./src/frontend/playground
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - "middleware"
    environment:
      - PORT=5000
    volumes:
      - ./src/frontend/playground:/app
    networks:
      - semapps
    ports:
      - "5000:5000"
    expose:
      - "5000"

volumes:
  rdf_data:
  staging:
networks:
  semapps:
    name: semapps_network
