version: "3.5"
services:
  fuseki:
    # user: fuseki
    image: stain/jena-fuseki
    container_name: fuseki
    restart: always
    volumes:
      - rdf_data:/fuseki
      - staging:/staging
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: "admin"
volumes:
  rdf_data:
  staging:
