name: Prettier formatting

on:
  pull_request:
    paths:
      - '**.css'
      - '**.js'

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install NPM packages
        run: make install

      - name: Run prettier
        run: make prettier

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic prettier
          branch: ${{ github.head_ref }}
          push_options: --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
